service: dynamo-stream-lab

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
            

functions:
  readStream:
    handler: handler.handler
    events:
      - stream:
          type: dynamodb
          arn: ARN-DYNAMODB-STREAM
          batchSize: 1
          maximumRetryAttempts: 10
          enabled: true